[project]
name = "gamejam-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Varshith A", email = "varshithanthagiri@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.5.3",
    "pillow>=12.3.0",
    "scipy>=1.18.1",
]

[project.scripts]
gamejam-2026 = "gamejam_2026:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
